name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black flake8
    
    - name: Code formatting check
      run: black --check src/
    
    - name: Linting
      run: flake8 src/ --max-line-length=127 --ignore=E203,W503
    
    - name: Run tests with coverage
      run: pytest src/tests/ --cov=src --cov-report=term-missing -v
    
    - name: Build Docker image
      run: docker build -t stock-alerter:test .
    
    - name: Test Docker container
      run: |
        docker run -d --name test-container -p 8000:8000 \
          -e ALPHA_VANTAGE_API_KEY=test_key \
          stock-alerter:test
        sleep 10
        curl -f http://localhost:8000/health
        docker stop test-container 